#!/bin/bash
set -e
swift --version

swift build -c release \
    --explicit-target-dependency-import-check=error \
    --build-tests

swift test -c release \
    --skip-build \
    --explicit-target-dependency-import-check=error
